title:              Carlos Pinto
email:              
description:        Personal Website
author:             Carlos Pinto
baseurl:            ''
url:                

# Social Profiles
twitter_username:  cpintoval 
github_username:   cpintoval
facebook_username:  
instagram_username:  
linkedin_username: cpintoval

# Google Analytics Tracking Code
google_analytics:   UA-71549946-1

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site